version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AWS_LOCATION_SERVICE_API_KEY=${AWS_LOCATION_SERVICE_API_KEY}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/geospatial_db
    volumes:
      - ./backend:/app
    depends_on:
      - db
    dns:
      - 8.8.8.8  # Google DNS
      - 8.8.4.4  # Google DNS backup

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=geospatial_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 